import type { MRT_Localization } from 'material-react-table';

export const MRT_VI: Partial<MRT_Localization> = {
    actions: 'Thao tác',
    and: 'và',
    cancel: 'Hủy',
    changeFilterMode: 'Thay đổi kiểu lọc',
    changeSearchMode: 'Thay đổi kiểu tìm kiếm',
    clearFilter: 'Xóa bộ lọc',
    clearSearch: 'Xóa tìm kiếm',
    clearSort: 'Xóa sắp xếp',
    clickToCopy: 'Nhấn để sao chép',
    copy: 'Sao chép',
    columnActions: 'Hành động cột',
    collapse: 'Thu gọn',
    collapseAll: 'Thu gọn tất cả',
    dropToGroupBy: 'Thả để nhóm theo {column}',
    edit: 'Chỉnh sửa',
    expand: 'Mở rộng',
    expandAll: 'Mở rộng tất cả',
    filterArrIncludes: 'Bao gồm',
    filterArrIncludesAll: 'Bao gồm tất cả',
    filterArrIncludesSome: 'Bao gồm một số',
    filterBetween: 'Khoảng',
    filterBetweenInclusive: 'Khoảng (bao gồm)',
    filterByColumn: 'Lọc theo {column}',
    filterContains: 'Chứa',
    filterEmpty: 'Rỗng',
    filterEndsWith: 'Kết thúc bằng',
    filterEquals: 'Bằng',
    filterEqualsString: 'Bằng',
    filterFuzzy: 'Mờ',
    filterGreaterThan: 'Lớn hơn',
    filterGreaterThanOrEqualTo: 'Lớn hơn hoặc bằng',
    filterInNumberRange: 'Trong khoảng',
    filterIncludesString: 'Chứa',
    filterIncludesStringSensitive: 'Chứa (phân biệt hoa thường)',
    filterLessThan: 'Nhỏ hơn',
    filterLessThanOrEqualTo: 'Nhỏ hơn hoặc bằng',
    filterMode: 'Chế độ lọc: {filterType}',
    filterNotEmpty: 'Không rỗng',
    filterNotEquals: 'Không bằng',
    filterStartsWith: 'Bắt đầu bằng',
    filterWeakEquals: 'Bằng (không chặt)',
    filteringByColumn: 'Lọc theo {column} - {filterType} {filterValue}',
    goToFirstPage: 'Trang đầu',
    goToLastPage: 'Trang cuối',
    goToNextPage: 'Trang sau',
    goToPreviousPage: 'Trang trước',
    grab: 'Kéo',
    groupByColumn: 'Nhóm theo {column}',
    groupedBy: 'Nhóm theo ',
    hideAll: 'Ẩn tất cả',
    hideColumn: 'Ẩn cột {column}',
    max: 'Tối đa',
    min: 'Tối thiểu',
    move: 'Di chuyển',
    noRecordsToDisplay: 'Không có dữ liệu để hiển thị',
    noResultsFound: 'Không tìm thấy kết quả',
    of: 'trên',
    or: 'hoặc',
    pin: 'Ghim',
    pinToLeft: 'Ghim sang trái',
    pinToRight: 'Ghim sang phải',
    resetColumnSize: 'Đặt lại kích thước cột',
    resetOrder: 'Đặt lại thứ tự',
    rowActions: 'Hành động hàng',
    rowNumber: '#',
    rowNumbers: 'Số hàng',
    rowsPerPage: 'Hàng mỗi trang',
    save: 'Lưu',
    search: 'Tìm kiếm',
    selectedCountOfRowCountRowsSelected: '{selectedCount} / {rowCount} hàng được chọn',
    select: 'Chọn',
    showAll: 'Hiện tất cả',
    showAllColumns: 'Hiện tất cả cột',
    showHideColumns: 'Hiện / Ẩn cột',
    showHideFilters: 'Hiện / Ẩn bộ lọc',
    showHideSearch: 'Hiện / Ẩn tìm kiếm',
    sortByColumnAsc: 'Sắp xếp tăng dần theo {column}',
    sortByColumnDesc: 'Sắp xếp giảm dần theo {column}',
    sortedByColumnAsc: 'Đang sắp xếp tăng dần theo {column}',
    sortedByColumnDesc: 'Đang sắp xếp giảm dần theo {column}',
    thenBy: ', sau đó theo ',
    toggleDensity: 'Thay đổi kích thước hàng',
    toggleFullScreen: 'Toàn màn hình',
    toggleSelectAll: 'Chọn tất cả',
    toggleSelectRow: 'Chọn hàng',
    toggleVisibility: 'Thay đổi hiển thị',
    ungroupByColumn: 'Bỏ nhóm theo {column}',
    unpin: 'Bỏ ghim',
    unpinAll: 'Bỏ ghim tất cả',
};


export const TEXTS = {
    STOCK_IN: {
        LIST_TITLE: 'QUẢN LÝ NHẬP KHO',
        LIST_SUBTITLE: 'Hệ thống quản lý chứng từ nhập kho hàng hóa vật tư',
        CREATE_NEW: 'TẠO PHIẾU MỚI',
        FORM_TITLE_CREATE: 'THÊM MỚI PHIẾU NHẬP KHO',
        FORM_TITLE_UPDATE: 'CẬP NHẬT PHIẾU NHẬP KHO',
        FORM_HEADER: 'CHI TIẾT PHIẾU NHẬP KHO',
        ITEM_LIST_TITLE: 'DANH MỤC HÀNG HÓA',
        ADD_ITEM: 'Thêm hàng',
        TOTAL_LABEL: 'THÀNH TIỀN:',
        TOTAL_WORDS: 'Bằng chữ:',
    },
    LABELS: {
        RECEIPT_NUMBER: 'Số chứng từ',
        RECEIPT_DATE: 'Ngày lập phiếu',
        COMPANY: 'Đơn vị (Công ty)',
        DEPARTMENT: 'Bộ phận',
        DELIVERER: 'Người giao hàng',
        RECEIVER: 'Người nhận hàng',
        DEBT_ACCOUNT: 'Nợ',
        CREDIT_ACCOUNT: 'Có',
        WAREHOUSE: 'Nhập tại kho',
        WAREHOUSE_LOCATION: 'Địa điểm kho',
        CREATOR: 'Người lập phiếu',
        KEEPER: 'Thủ kho',
        ACCOUNTANT: 'Kế toán trưởng',
        NOTE: 'Ghi chú',
        PRODUCT_CODE: 'Mã hàng hoá',
        PRODUCT_NAME: 'Tên hàng hoá',
        UNIT: 'Đơn vị tính',
        QTY_DOC: 'SL (Chứng từ)',
        QTY_ACTUAL: 'SL (Thực nhập)',
        PRICE: 'Đơn giá',
        REFERENCE_TYPE: 'Theo',
        REFERENCE_NUMBER: 'Số',
        REFERENCE_DATE: 'Ngày',
        REFERENCE_ISSUER: 'Của',
    },
    BUTTONS: {
        SAVE: 'Lưu phiếu nhập',
        CANCEL: 'Hủy bỏ',
        CONFIRM: 'Đồng ý',
        AGREE_DELETE: 'Đồng ý xóa',
        CLOSE: 'Đóng',
    },
    TABLE: {
        RECEIPT_NUMBER: 'Số chứng từ',
        DATE: 'Ngày lập',
        DELIVERER: 'Người giao hàng',
        WAREHOUSE: 'Kho nhập',
        TOTAL: 'Tổng tiền (VNĐ)',
        ACTIONS: 'Thao tác',
    },
    VALIDATION: {
        REQUIRED: 'Bắt buộc nhập',
        MAX_50: 'Tối đa 50 ký tự',
        MAX_255: 'Tối đa 255 ký tự',
        PRODUCT_NAME_REQ: 'Tên hàng là bắt buộc',
        NUMBER_ERROR: 'Phải là số',
        MIN_0: '>= 0',
        MIN_1_ITEM: 'Cần ít nhất 1 mặt hàng',
    }
};
